name: Daily Web Scraper

on:
  schedule:
    # Schedule to run daily at 07:00 UTC
    - cron:  '0 7 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4

    - name: Run scraper
      run: python scraper.py 

    # Optional: Add steps to store or process the data, like pushing to a branch or uploading to an external storage service
